apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-mul
  labels:
    app: daemonset-mul
spec:
  selector:
    matchLabels:
      app: daemonset-mul
  template:
    metadata:
      labels:
        app: daemonset-mul
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 11443
          name: https-port
        volumeMounts:
        - name: vol
          mountPath: /input
      volumes:
      - name: vol
        hostPath:
          path: /var/log/syslog